In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
FifaDB = pd.read_csv('NewFifa.csv')

In [5]:
from sklearn.model_selection import train_test_split
fifatrain, fifatest = train_test_split(FifaDB, test_size = 0.25)

In [6]:
FifaDB

,Name,Overall,Potential,Value,Wage,Weak Foot,Skill Moves,Position,Jersey Number,Height,...,Body Type_Akinfenwa,Body Type_C. Ronaldo,Body Type_Courtois,Body Type_Lean,Body Type_Messi,Body Type_Neymar,Body Type_Normal,Body Type_PLAYER_BODY_TYPE_25,Body Type_Shaqiri,Body Type_Stocky
0,L. Messi,94,94,€110.5M,€565K,4.0,4.0,RF,10.0,174,...,0,0,0,0,1,0,0,0,0,0
1,Cristiano Ronaldo,94,94,€77M,€405K,4.0,5.0,ST,7.0,189,...,0,1,0,0,0,0,0,0,0,0
2,Neymar Jr,92,93,€118.5M,€290K,5.0,5.0,LW,10.0,180,...,0,0,0,0,0,1,0,0,0,0
3,De Gea,91,93,€72M,€260K,3.0,1.0,GK,1.0,195,...,0,0,0,1,0,0,0,0,0,0
4,K. De Bruyne,91,92,€102M,€355K,5.0,4.0,RCM,7.0,155,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18142,J. Lundstram,47,65,€60K,€1K,2.0,2.0,CM,22.0,180,...,0,0,0,1,0,0,0,0,0,0
18143,N. Christoffersson,47,63,€60K,€1K,2.0,2.0,ST,21.0,192,...,0,0,0,0,0,0,1,0,0,0
18144,B. Worman,47,67,€60K,€1K,3.0,2.0,ST,33.0,177,...,0,0,0,0,0,0,1,0,0,0
18145,D. Walker-Rice,47,66,€60K,€1K,3.0,2.0,RW,34.0,155,...,0,0,0,1,0,0,0,0,0,0
18146,G. Nugent,46,66,€60K,€1K,3.0,2.0,CM,33.0,155,...,0,0,0,1,0,0,0,0,0,0

In [7]:
list_lengths = np.array(FifaDB['Height'])
empty_list = []
for x in list_lengths:
    splitted_values = x.split("'")
    feet = (float(x[0])) + (float(x[2])/10)
    centimeters = feet * 30.48
    empty_list.append(round(centimeters))

print(empty_list)

AttributeError: 'numpy.int64' object has no attribute 'split'

In [ ]:
list_wages = FifaDB['Wage']
wages = []
for i in list_wages:
    hoi = i.strip('K').strip('€')
    wage = int(hoi) * 1000
    wages.append(wage)
print(wages)

In [6]:
list_value = FifaDB['Value']
list_new_values = []

for v in list_value[1:10]:
    if v[-1] == 'M':
        strip_value = v.strip('M').strip('€')
        new_value = strip_value * 1000000
        list_new_values.append(new_value)
print(list_new_values)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [7]:
list_value = FifaDB['Value']
list_new_values = []

for v in list_value[1:10]:
    if v[-1] == 'M':
        strip_value = v.strip('M').strip('€')
        new_value = strip_value * 1000000
        list_new_values.append(new_value)
print(list_new_values)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)