In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
FifaDB = pd.read_csv('NewFifa.csv')

In [3]:
from sklearn.model_selection import train_test_split
fifatrain, fifatest = train_test_split(FifaDB, test_size = 0.25)

In [4]:
FifaDB

,Name,Overall,Potential,Value,Wage,Weak Foot,Skill Moves,Position,Jersey Number,Height,...,Body Type_Akinfenwa,Body Type_C. Ronaldo,Body Type_Courtois,Body Type_Lean,Body Type_Messi,Body Type_Neymar,Body Type_Normal,Body Type_PLAYER_BODY_TYPE_25,Body Type_Shaqiri,Body Type_Stocky
0,L. Messi,94,94,€110.5M,€565K,4.0,4.0,RF,10.0,5'7,...,0,0,0,0,1,0,0,0,0,0
1,Cristiano Ronaldo,94,94,€77M,€405K,4.0,5.0,ST,7.0,6'2,...,0,1,0,0,0,0,0,0,0,0
2,Neymar Jr,92,93,€118.5M,€290K,5.0,5.0,LW,10.0,5'9,...,0,0,0,0,0,1,0,0,0,0
3,De Gea,91,93,€72M,€260K,3.0,1.0,GK,1.0,6'4,...,0,0,0,1,0,0,0,0,0,0
4,K. De Bruyne,91,92,€102M,€355K,5.0,4.0,RCM,7.0,5'11,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18142,J. Lundstram,47,65,€60K,€1K,2.0,2.0,CM,22.0,5'9,...,0,0,0,1,0,0,0,0,0,0
18143,N. Christoffersson,47,63,€60K,€1K,2.0,2.0,ST,21.0,6'3,...,0,0,0,0,0,0,1,0,0,0
18144,B. Worman,47,67,€60K,€1K,3.0,2.0,ST,33.0,5'8,...,0,0,0,0,0,0,1,0,0,0
18145,D. Walker-Rice,47,66,€60K,€1K,3.0,2.0,RW,34.0,5'10,...,0,0,0,1,0,0,0,0,0,0
18146,G. Nugent,46,66,€60K,€1K,3.0,2.0,CM,33.0,5'10,...,0,0,0,1,0,0,0,0,0,0

In [5]:
list_lengths1 = np.array(FifaDB['Height'])
empty_list = []
for x in list_lengths1:
    splitted_values = x.split("'")
    feet = (float(x[0])) + (float(x[2])/10)
    centimeters = feet * 30.48
    
    
return empty_list.append(centimeters)
print(empty_list)

SyntaxError: 'return' outside function (<ipython-input-5-3345bc102943>, line 9)