In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
FifaDB = pd.read_csv('NewFifa.csv')

In [3]:
from sklearn.model_selection import train_test_split
fifatrain, fifatest = train_test_split(FifaDB, test_size = 0.25)

In [21]:
FifaDB

,Name,Overall,Potential,Value,Wage,Weak Foot,Skill Moves,Jersey Number,Height,Weight,...,Body Type_Akinfenwa,Body Type_C. Ronaldo,Body Type_Courtois,Body Type_Lean,Body Type_Messi,Body Type_Neymar,Body Type_Normal,Body Type_PLAYER_BODY_TYPE_25,Body Type_Shaqiri,Body Type_Stocky
0,L. Messi,94,94,€110.5M,565000,4.0,4.0,10.0,174,159lbs,...,0,0,0,0,1,0,0,0,0,0
1,Cristiano Ronaldo,94,94,€77M,405000,4.0,5.0,7.0,189,183lbs,...,0,1,0,0,0,0,0,0,0,0
2,Neymar Jr,92,93,€118.5M,290000,5.0,5.0,10.0,180,150lbs,...,0,0,0,0,0,1,0,0,0,0
3,De Gea,91,93,€72M,260000,3.0,1.0,1.0,195,168lbs,...,0,0,0,1,0,0,0,0,0,0
4,K. De Bruyne,91,92,€102M,355000,5.0,4.0,7.0,155,154lbs,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18142,J. Lundstram,47,65,€60K,1000,2.0,2.0,22.0,180,134lbs,...,0,0,0,1,0,0,0,0,0,0
18143,N. Christoffersson,47,63,€60K,1000,2.0,2.0,21.0,192,170lbs,...,0,0,0,0,0,0,1,0,0,0
18144,B. Worman,47,67,€60K,1000,3.0,2.0,33.0,177,148lbs,...,0,0,0,0,0,0,1,0,0,0
18145,D. Walker-Rice,47,66,€60K,1000,3.0,2.0,34.0,155,154lbs,...,0,0,0,1,0,0,0,0,0,0
18146,G. Nugent,46,66,€60K,1000,3.0,2.0,33.0,155,176lbs,...,0,0,0,1,0,0,0,0,0,0

In [5]:
list_lengths = np.array(FifaDB['Height'])
empty_list = []
for x in list_lengths:
    splitted_values = x.split("'")
    feet = (float(x[0])) + (float(x[2])/10)
    centimeters = feet * 30.48
    empty_list.append(round(centimeters))

print(empty_list)

AttributeError: 'numpy.int64' object has no attribute 'split'

In [20]:
list_wages = FifaDB['Wage']
wages = []
for i in list_wages:
    hoi = i.strip('K').strip('€')
    wage = int(hoi) * 1000
    wages.append(wage)
    
FifaDB['Wage'] = wages

In [19]:
list_values = FifaDB['Value']
values = []
for i in list_values[:10:]:
    if(i[-1]) == 'M':
        print(i.split('.').strip(''))

AttributeError: 'list' object has no attribute 'strip'

TypeError: 'DataFrame' object is not callable